### ISSUE TITLE
希望能够支持UDP穿透（UDP Associate）

### ISSUE THREAD

**Issue by huawy** [shadowsocks/shadowsocks-go#42]
nodejs版本是支持这个的，但是我喜欢用go版本，因为安装使用更方便。

**Comment by a1328788808** [comment]
@lixin9311   能详细说下-u参数怎么加吗？或者贴一份/etc/init.d/shadowsocks文件？谢谢。小白一枚，还不太会用。

**Comment by a1328788808** [comment]
@lixin9311 这是/etc/init.d/shadowsocks里的内容，-u应该加在哪里呢？
#! /bin/bash
#===============================================================================================
#   System Required:  Debian or Ubuntu (32bit/64bit)
#   Description:  Install Shadowsocks(go) for Debian or Ubuntu
#   Author: tennfy <admin@tennfy.com>
#   Intro:  http://www.tennfy.com
#===============================================================================================

clear
echo "#############################################################"
echo "# Install Shadowsocks(go) for Debian or Ubuntu (32bit/64bit)"
echo "# Intro: http://www.tennfy.com"
echo "#"
echo "# Author: tennfy <admin@tennfy.com>"
echo "#"
echo "#############################################################"
echo ""

# Make sure only root can run our script
if [[ $EUID -ne 0 ]]; then
   echo "Error:This script must be run as root!" 1>&2
   exit 1
fi

cd $HOME

# install
apt-get update
apt-get install -y --force-yes git mercurial curl

#install go enviroment
ldconfig
if [ $(getconf WORD_BIT) = '32' ] && [ $(getconf LONG_BIT) = '64' ] ; then
	wget http://golang.org/dl/go1.3.linux-amd64.tar.gz --no-check-certificate
	tar xf go1.3.linux-amd64.tar.gz
	rm go1.3.linux-amd64.tar.gz
else
	wget http://golang.org/dl/go1.3.linux-386.tar.gz --no-check-certificate
	tar xf go1.3.linux-386.tar.gz
	rm go1.3.linux-386.tar.gz
fi

echo "export GOROOT=\$HOME/go" >> ~/.profile
echo "PATH=$PATH:\$GOROOT/bin" >> ~/.profile
source ~/.profile
mkdir ~/gocode
echo "export GOPATH=\$HOME/gocode" >> ~/.profile
echo "PATH=\$PATH:\$GOPATH/bin" >> ~/.profile
source ~/.profile

#download shadowsocks-go

go get github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-server

chmod +x /root/gocode/bin/shadowsocks-server
# Get IP address(Default No.1)
IP=`curl -s checkip.dyndns.com | cut -d' ' -f 6  | cut -d'<' -f 1`
if [ -z $IP ]; then
   IP=`curl -s ifconfig.me/ip`
fi

#config setting
echo "#############################################################"
echo "#"
echo "# Please input your shadowsocks server_port and password"
echo "#"
echo "#############################################################"
echo ""
echo "input server_port(443 is suggested):"
read serverport
echo "input password:"
read shadowsockspwd

# Config shadowsocks
cat > /root/gocode/bin/config.json<<-EOF
{
    "server":"${IP}",
    "server_port":${serverport},
    "local_port":1080,
    "password":"${shadowsockspwd}",
    "timeout":60,
    "method":"aes-256-cfb"
}
EOF

cat > /etc/init.d/shadowsocks<<-"EOF"
#!/bin/bash
# Start/stop shadowsocks.
#
### BEGIN INIT INFO
# Provides:          shadowsocks
# Required-Start:
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: shadowsocks is a lightweight tunneling proxy
# Description:       Modified from Linode's nginx fastcgi startup script
### END INIT INFO

# Note: this script requires sudo in order to run shadowsocks as the specified
# user.

BIN=/root/gocode/bin/shadowsocks-server
CONFIG_FILE=/root/gocode/bin/config.json
LOG_FILE=/var/log/shadowsocks
USER=root
GROUP=root
PID_DIR=/var/run
PID_FILE=$PID_DIR/shadowsocks.pid
RET_VAL=0

[ -x $BIN ] || exit 0

check_running() {
  if [[ -r $PID_FILE ]]; then
    read PID <$PID_FILE
    if [[ -d "/proc/$PID" ]]; then
      return 0
    else
      rm -f $PID_FILE
      return 1
    fi
  else
    return 2
  fi
}

do_status() {
  check_running
  case $? in
    0)
      echo "shadowsocks running with PID $PID"
      ;;
    1)
      echo "shadowsocks not running, remove PID file $PID_FILE"
      ;;
    2)
      echo "Could not find PID file $PID_FILE, shadowsocks does not appear to be running"
      ;;
  esac
  return 0
}

do_start() {
  if [[ ! -d $PID_DIR ]]; then
    echo "creating PID dir"
    mkdir $PID_DIR || echo "failed creating PID directory $PID_DIR"; exit 1
    chown $USER:$GROUP $PID_DIR || echo "failed creating PID directory $PID_DIR"; exit 1
    chmod 0770 $PID_DIR
  fi
  if check_running; then
    echo "shadowsocks already running with PID

**Comment by a1328788808** [comment]
@lixin9311 上面的发错了，这才是/etc/init.d/shadowsocks里的内容，-u应该加在哪里呢？
#!/bin/bash
# Start/stop shadowsocks.
#
### BEGIN INIT INFO
# Provides:          shadowsocks
# Required-Start:
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: shadowsocks is a lightweight tunneling proxy
# Description:       Modified from Linode's nginx fastcgi startup script
### END INIT INFO

# Note: this script requires sudo in order to run shadowsocks as the specified
# user.

BIN=/root/gocode/bin/shadowsocks-server
CONFIG_FILE=/root/gocode/bin/config.json
LOG_FILE=/var/log/shadowsocks
USER=root
GROUP=root
PID_DIR=/var/run
PID_FILE=$PID_DIR/shadowsocks.pid
RET_VAL=0

[ -x $BIN ] || exit 0

check_running() {
  if [[ -r $PID_FILE ]]; then
    read PID <$PID_FILE
    if [[ -d "/proc/$PID" ]]; then
      return 0
    else
      rm -f $PID_FILE
      return 1
    fi
  else
    return 2
  fi
}

do_status() {
  check_running
  case $? in
    0)
      echo "shadowsocks running with PID $PID"
      ;;
    1)
      echo "shadowsocks not running, remove PID file $PID_FILE"
      ;;
    2)
      echo "Could not find PID file $PID_FILE, shadowsocks does not appear to be                                                                                                  running"
      ;;
  esac
  return 0
}

do_start() {
  if [[ ! -d $PID_DIR ]]; then
    echo "creating PID dir"
    mkdir $PID_DIR || echo "failed creating PID directory $PID_DIR"; exit 1
    chown $USER:$GROUP $PID_DIR || echo "failed creating PID directory $PID_DIR"                                                                                                 ; exit 1
    chmod 0770 $PID_DIR
  fi
  if check_running; then
    echo "shadowsocks already running with PID $PID"
    return 0
  fi
  if [[ ! -r $CONFIG_FILE ]]; then
    echo "config file $CONFIG_FILE not found"
    return 1
  fi
  echo "starting shadowsocks"
  # sudo will set the group to the primary group of $USER
  sudo -u $USER $BIN -c $CONFIG_FILE >>$LOG_FILE &
  PID=$!
  echo $PID > $PID_FILE
  sleep 0.3
  if ! check_running; then
    echo "start failed"
    return 1
  fi
  echo "shadowsocks running with PID $PID"
  return 0
}

do_stop() {
  if check_running; then
    echo "stopping shadowsocks with PID $PID"
    kill $PID
    rm -f $PID_FILE
  else
    echo "Could not find PID file $PID_FILE"
  fi
}

do_restart() {
  do_stop
  do_start
}

case "$1" in
  start|stop|restart|status)
    do_$1
    ;;
  *)
    echo "Usage: shadowsocks {start|stop|restart|status}"
    RET_VAL=1
    ;;
esac

exit $RET_VAL

**Comment by lixin9311** [comment]
https://github.com/lixin9311/shadowsocks-go/blob/dd11e3ccfeedc1ef25f2624f18c6178fac983711/cmd/shadowsocks-server/shadowsocks-server_linux_amd64
用这个二进制版本
sudo -u $USER $BIN -c 这在-c后面 加-u
就是sudo -u $USER $BIN -c -u

**Comment by a1328788808** [comment]
@lixin9311   官方的shadowsocks-server可以运行，加了-u不能运行。 你提供的shadowsocks-server_linux_amd64，无论加不加-u，服务端都无法启动。重装了好几次都不行。(把shadowsocks-server_linux_amd64名字改成shadowsocks-server也试过了)

**Comment by lixin9311** [comment]
go get github.com/lixin9311/shadowsocks-go/cmd/shadowsocks-server
在你的环境中重新编译吧

**Comment by a1328788808** [comment]
加了 -u 参数后
root@default:~# /etc/init.d/shadowsocks start
starting shadowsocks
must specify both port and password
start failed
不加-u才能启动服务端。。

**Comment by lixin9311** [comment]
手机上编辑的 抱歉
sudo -u $USER $BIN -c $CONFIG_FILE >>$LOG_FILE &
应该是
sudo -u $USER $BIN -u -c $CONFIG_FILE >>$LOG_FILE &

**Comment by a1328788808** [comment]
@lixin9311 崩溃了。又安了一遍，还不行。大神有没有时间，帮我看看。

**Comment by a1328788808** [comment]
@lixin9311   我邮箱a1328788808@gmail.com

**Comment by lixin9311** [comment]
用screen或者tmux开吧，这样报错信息就都能看到。
我最近新改了点东西还没测试，不过不应该有问题的。
如果不是非得用go，建议使用libev，毕竟golang里面的UDP socket弄得很不舒服

**Comment by a1328788808** [comment]
@lixin9311   
goroutine 27 [IO wait]:
net.runtime_pollWait(0xb75ff220, 0x72, 0x0)
        /usr/local/go/src/pkg/runtime/netpoll.goc:146 +0x62
net.(*pollDesc).Wait(0x18430038, 0x72, 0x0, 0x0)
        /usr/local/go/src/pkg/net/fd_poll_runtime.go:84 +0x48
net.(*pollDesc).WaitRead(0x18430038, 0x0, 0x0)
        /usr/local/go/src/pkg/net/fd_poll_runtime.go:89 +0x46
net.(*netFD).Read(0x18430000, 0x18481000, 0x1000, 0x1000, 0x0, 0xb75fe248, 0x
b)
        /usr/local/go/src/pkg/net/fd_unix.go:232 +0x28d
net.(*conn).Read(0x18400148, 0x18481000, 0x1000, 0x1000, 0x827ba00, 0x0, 0x0)
        /usr/local/go/src/pkg/net/net.go:122 +0xc6
github.com/lixin9311/shadowsocks-go/shadowsocks.(*UDPConn).resRequest(0x18400
218, 0x3c, 0x1840e8e0, 0x18475000, 0x3c, 0x1000)
        /root/gocode/src/github.com/lixin9311/shadowsocks-go/shadowsocks/conn
.go:111 +0x994
created by github.com/lixin9311/shadowsocks-go/shadowsocks.(*UDPConn).HandleU
root@default:~#
        /root/gocode/src/github.com/lixin9311/shadowsocks-go/shadowsocks/conn
.go:145 +0xd6
加了-u启动以后，对话框自动生成了这些。前面还有goroutine 24 goroutine 23 等等。内容都差不多

**Comment by a1328788808** [comment]
@lixin9311
https://github.com/lixin9311/shadowsocks-go/blob/dd11e3ccfeedc1ef25f2624f18c6178fac983711/cmd/shadowsocks-server/shadowsocks-server_linux_amd64
用这个搞定了，感谢！不过新版还是有问题。

**Comment by huawy** [comment]
@lixin9311 多谢，昨天重新编译了i386版本的server，可以用了，能够支持udp relay，不过客户端还是不支持，换了c#版本的客户端就没问题了。

**Comment by lixin9311** [comment]
最新版本有点问题，在win上不会出错，在linux上会出错，是因为一个指针引用的错误导致。
现在改好了，顺便测试一下openvpn over ss with udp，测试号了再pull

**Comment by a1328788808** [comment]
@lixin9311 辛苦了。

**Comment by lixin9311** [comment]
windows环境下，OpenVPN udp模式通过Shadowsocks-csharp客户端连接，服务器端分别用libev和go版测试均失败
TCP模式正常。
放假手边没安卓和路由器设备，没法测试udp relay是否正常工作。不过应该没问题，如果出错还是回滚到
https://github.com/lixin9311/shadowsocks-go/tree/dd11e3ccfeedc1ef25f2624f18c6178fac983711
这个版本跑了1个月也没坏。

**Comment by lixin9311** [comment]
Shadowsocks-csharp不支持udp
qt+python shadowsocks貌似支持有问题
所以没办法测试openvpn over ss w/ udp
现在我只是试了一下ss-tunnel 正常。

**Comment by madeye** [comment]
之前测下来 QQ 对 UDP Socks5 支持最靠谱，可以试一试。

**Comment by lixin9311** [comment]
现在是客户端没有能够好好支持socks5 udp命令的。
下一步就是把go版客户端加入udp功能，再测试openvpn。

**Comment by a1328788808** [comment]
@lixin9311   那现在用哪个版本的二进制文件呢?

**Comment by lixin9311** [comment]
最新的。安卓客户端和ss-tunnel应该能正确工作。
其他的再等等吧

**Comment by lixin9311** [comment]
也正在考虑加入socks5 BIND。

2015-01-29 17:11 GMT+08:00 lee xin <lixin9311@gmail.com>:

**Comment by clowwindy** [comment]
QQ 的 socks 5 支持有一些问题，比如有时没有填用户名密码还是会用一个奇怪的用户名试图验证。OpenVPN 和 dante 带的 socksify 都工作正常，socksify 更可以配合几乎任何软件使用，如 dig。现在 Python 版的 UDP 单元测试就是用 socksify 做客户端。

**Comment by lixin9311** [comment]
可能是在win上有问题。
测试的时候本地用python的客户端，服务器用libev，在服务器端虽然能正确接到并转发udp包，不过往回转发就把客户端地址变成:ffff:ipv4 addr这种格式。当然就收不到了。
总之有一些奇奇怪怪的问题，可能还是ss客户端这边的事。

**Comment by a1328788808** [comment]
@lixin9311 能不能给个二进制文件的下载地址?

**Comment by lixin9311** [comment]
@a1328788808
# on server
go get github.com/lixin9311/shadowsocks-go/cmd/shadowsocks-server

**Comment by a1328788808** [comment]
@lixin9311 谢谢

**Comment by LazyZhu** [comment]
@lixin9311 Make a pull?
@clowwindy 可惜ss-redir不支持udp, 不然dns直接就可以省掉一个udp转tcp的程序了.

**Comment by lixin9311** [comment]
现在只是测试过ss-tunnel，处理dns请求是没问题的。
其他的，例如openvpn，这样的较大的负载还没测试。

**Comment by onewilk** [comment]
@lixin9311 您好，我在使用您上面提供的二进制下载地址的时候报错如下
[root@wilk go]# go get github.com/lixin9311/shadowsocks-go/cmd/shadowsocks-server
# github.com/lixin9311/shadowsocks-go/cmd/shadowsocks-server
gopkg/src/github.com/lixin9311/shadowsocks-go/cmd/shadowsocks-server/server.go:344: undefined: shadowsocks.NewUDPConn

我对go完全没有了解过，想问下该怎么解决？

**Comment by onewilk** [comment]
@lixin9311 还有个问题是，我vps服务端安装go版本的ss，但我的路由器用libev的ss可以么？还是说一定也要用go版本的？

**Comment by lixin9311** [comment]
因因为发现了一个udprelay实现上的问题，所以现在先撤回了。建议还是使用libev或者python。
修补工作已经基本完成，测试显示基本和python版的速度相同，再稍微改进改进就可以发出来了。

版本可以随意搭配。

**Comment by onewilk** [comment]
@lixin9311 嗯...我现在用原版的go,配合dnsmasq做我路由器的chinadns上游,感觉很不错...期待你的版本早日放出...

**Comment by riodejacyman** [comment]
以前用tennfy的那个脚本，改主包加参数可以安装和使用，但是已经有一个多月装了用不了了。

**Comment by clowwindy** [comment]
UDP 端口映射的逻辑做了一个调整： https://github.com/shadowsocks/shadowsocks-libev/issues/337

**Comment by lixin9311** [comment]
Go的是full cone
NAT。假定客户端会把同一个应用的从同一udp端口发的数据都通过同一个udp端口转发到代理服务器上。不管目标是哪服务器都会从同一udp个端口转发。这样就双向可见了。
2015年7月12日 22:07于 "clowwindy" <notifications@github.com>写道：
